// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(FoodOrderDBContext))]
    partial class FoodOrderDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDonHang")
                        .HasName("PK__ChiTietD__4B0B45DD7B737F2C");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaMonAn");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.DanhGium", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGia__AA9515BF478FB2A7");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhaHang");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebAPI.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584AD01657466");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaNhaHang");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang");

                    b.HasIndex("MaMonAn");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.MonAn", b =>
                {
                    b.Property<int>("MaMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonAn"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MaNhaHang")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenMonAn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlhinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("URLHinhAnh");

                    b.HasKey("MaMonAn")
                        .HasName("PK__MonAn__B1171625EE1AB43B");

                    b.HasIndex("MaNhaHang");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D76215A60F46");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__NguoiDun__55F68FC00384FA69")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D105343961A706")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.NhaHang", b =>
                {
                    b.Property<int>("MaNhaHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhaHang")
                        .HasName("PK__NhaHang__7CE4848A27A5C5BB");

                    b.ToTable("NhaHang", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__ThanhToa__D4B258447A4ADE85");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("WebAPI.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaDon__47DBAE45");

                    b.HasOne("WebAPI.Models.MonAn", "MaMonAnNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaMonAn")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaMon__48CFD27E");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaMonAnNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.DanhGium", b =>
                {
                    b.HasOne("WebAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaNguoi__5165187F");

                    b.HasOne("WebAPI.Models.NhaHang", "MaNhaHangNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNhaHang")
                        .IsRequired()
                        .HasConstraintName("FK__DanhGia__MaNhaHa__52593CB8");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaNhaHangNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.DonHang", b =>
                {
                    b.HasOne("WebAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__MaNguoi__440B1D61");

                    b.HasOne("WebAPI.Models.NhaHang", "MaNhaHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNhaHang")
                        .IsRequired()
                        .HasConstraintName("FK__DonHang__MaNhaHa__44FF419A");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaNhaHangNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.GioHang", b =>
                {
                    b.HasOne("WebAPI.Models.MonAn", "MaMonAnNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaMonAn")
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_MonAn");

                    b.HasOne("WebAPI.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_GioHang_NguoiDung");

                    b.Navigation("MaMonAnNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.MonAn", b =>
                {
                    b.HasOne("WebAPI.Models.NhaHang", "MaNhaHangNavigation")
                        .WithMany("MonAns")
                        .HasForeignKey("MaNhaHang")
                        .IsRequired()
                        .HasConstraintName("FK__MonAn__MaNhaHang__403A8C7D");

                    b.Navigation("MaNhaHangNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.ThanhToan", b =>
                {
                    b.HasOne("WebAPI.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__MaDon__4CA06362");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("WebAPI.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("WebAPI.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebAPI.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebAPI.Models.NhaHang", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DonHangs");

                    b.Navigation("MonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
